model:
  model_name: "GSDG"
  lama: 0.95
  d_k: 16
  topk: 8

data_input:
  dataset_name: "indian"

data_split:
  samples_type: fixed
  train_num: 10
  train_ratio: 0.05
  superpixel_scale: 100

result_output:
  path_weight: ResultsModel/
  path_result: Results/